package com.kinesysApp.kinesys.enumeraciones;



public enum Provincia {
    MENDOZA,SAN_JUAN,SAN_LUIS,LA_RIOJA,SANTIAGO_DEL_ESTERO,
    JUJUY,CHACO,FORMOSA,SALTA,TUCUMAN,CATAMARCA,
    MISIONES,CORRIENTES,ENTRE_RIOS,
    CHUBUT,SANTA_CRUZ,NEUQUEN,TIERRA_DEL_FUEGO,RIO_NEGRO,
    LA_PAMPA,BUENOS_AIRES,SANTA_FE, Name, CORDOBA
}
